# gitea.yml
---
apiVersion: v1
kind: Namespace
metadata:
  name: gitea
  namespace: gitea
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitea
  namespace: gitea
spec:
  volumeName: gitea
  resources:
    requests:
      storage: 5Gi
  accessModes:
    - ReadWriteMany
---
apiVersion: v1
data:
  app.ini: |
    APP_NAME = Gitea
    RUN_USER = git
    RUN_MODE = prod
    WORK_PATH = /data/gitea/

    [security]
    INTERNAL_TOKEN     = {{ internal_token }}
    INSTALL_LOCK       = true
    SECRET_KEY         = {{ secret_key }}
    PASSWORD_HASH_ALGO = pbkdf2
    
    [database]
    DB_TYPE  = postgres
    HOST     = postgres-cluster:5432
    NAME     = giteadb
    # USER     = gitea
    USER     = postgres
    # PASSWD   = $(kubectl get secrets postgres-gitea-user -o jsonpath='{.data.password}' | base64 -d)
    PASSWD   = {{ postgres_superuser_password }}
    SCHEMA   = 
    SSL_MODE = disable
    CHARSET  = utf8
    PATH     = /app/gitea/data/gitea.db
    LOG_SQL  = false

    [repository]
    ROOT = /data/gitea/gitea-repositories
    ENABLE_PUSH_CREATE_USER = true
    
    [server]
    SSH_DOMAIN       = gitea.mksybr.com
    DOMAIN           = gitea.mksybr.com
    HTTP_PORT        = 3000
    ROOT_URL         = https://gitea.mksybr.com/
    SSH_DOMAIN       = gitea.mksybr.com
    DISABLE_SSH      = false
    START_SSH_SERVER = true
    SSH_PORT         = 2222
    LFS_START_SERVER = true
    LFS_CONTENT_PATH = /data/gitea/lfs
    LFS_JWT_SECRET   = {{ lfs_secret }}
    OFFLINE_MODE     = false

    [mailer]
    ENABLED = false

    [service]
    REGISTER_EMAIL_CONFIRM            = false
    ENABLE_NOTIFY_MAIL                = false
    DISABLE_REGISTRATION              = false
    ALLOW_ONLY_EXTERNAL_REGISTRATION  = false
    ENABLE_CAPTCHA                    = false
    REQUIRE_SIGNIN_VIEW               = true
    DEFAULT_KEEP_EMAIL_PRIVATE        = true
    DEFAULT_ALLOW_CREATE_ORGANIZATION = true
    DEFAULT_ENABLE_TIMETRACKING       = true
    NO_REPLY_ADDRESS                  = noreply.localhost

    [picture]
    DISABLE_GRAVATAR        = false
    ENABLE_FEDERATED_AVATAR = true

    [openid]
    ENABLE_OPENID_SIGNIN = true
    ENABLE_OPENID_SIGNUP = true

    [oauth2_client]
    ENABLE_AUTO_REGISTRATION = true
    USERNAME = email

    [session]
    PROVIDER = db # TODO(Malik): redis/redis-cluster

    [log]
    MODE      = console
    LEVEL     = info
    ROOT_PATH = /data/gitea/log
    ROUTER    = console

    [cors]
    ENABLED   = false

    [api]
    ENABLE_SWAGGER = false

    [metrics]
    ENABLED    = true
    ;; TOKEN      = create and get prometheus secret

    [cron]
    ENABLED      = true

    [cache]
    # ADAPTER    = redis # TODO(Malik): redis

kind: ConfigMap
metadata:
  name: gitea-config
  namespace: gitea
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitea
  namespace: gitea
spec:
  selector:
    matchLabels:
      app: gitea
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: gitea
    spec:
      initContainers:
      - name: inject-postgres-secret
        image: busybox:1.28
        command: [
        "sh", "-c", "
        SRC=/tmp/gitea.ini
        DEST=/gitea/conf/app.ini
        mkdir -p $(dirname $DEST); cp $SRC $DEST;
        sed -ie s/{{ internal_token }}/$(gitea_internal_token)/g $DEST;
        sed -ie s/{{ secret_key }}/$(gitea_secret_key)/g $DEST;
        sed -ie s/{{ lfs_secret }}/$(gitea_lfs_secret)/g $DEST;
        sed -ie s/{{ postgres_superuser_password }}/$(postgres_superuser_password)/g $DEST", 
        "|| sleep 600"]
        env:
        - name: gitea_internal_token
          valueFrom:
            secretKeyRef:
              key: gitea-internal-token
              name: password
        - name: gitea_secret_key 
          valueFrom:
            secretKeyRef:
              key: password
              name: gitea-secret-key
        - name: gitea_lfs_secret
          valueFrom:
            secretKeyRef:
              key: password
              name: gitea-lfs-secret
        - name: postgres_superuser_password
          valueFrom:
            secretKeyRef:
              key: superuser-password
              name: postgres-cluster
        volumeMounts:
        - name: config-scratchpad
          mountPath:  /gitea/conf
          subPath: app.ini
          readOnly: false
        - mountPath: /tmp/gitea.ini
          name: gitea-config-file
          readOnly: false
          subPath: gitea.ini
      - name: setup-database
        image: ongres/postgres-util
        args:
        - psql
        - postgres://postgres:$(POSTGRES_SUPERUSER_PASSWORD)@postgres-cluster
        - -c
        - CREATE USER IF NOT EXISTS gitea WITH PASSWORD '$(POSTGRES_GITEA_PASSWORD)' CREATEDB;
        env:
        - name: POSTGRES_SUPERUSER_PASSWORD
          valueFrom: 
            secretKeyRef:
              name: postgres-cluster 
              key: superuser-password
        - name: POSTGRES_GITEA_PASSWORD
          valueFrom: 
             secretKeyRef:
              name: postgres-gitea-user
              key: password
      containers:
        - name: gitea
          image: gitea/gitea:1.15
          ports:
            - containerPort: 3000
              hostPort: 3001
              protocol: TCP
              name: http
            - containerPort: 22
              hostPort: 2222
              protocol: TCP
              name: ssh
          volumeMounts:
          - mountPath: /data
            name: gitea
          - mountPath: /data/gitea/conf/
            name: config-scratchpad
            readOnly: true
            subPath: app.ini
      restartPolicy: Always
      volumes:
        - name: gitea
          persistentVolumeClaim:
            claimName: gitea
        - name: gitea-config-file
          configMap:
            name: gitea-config
            items:
              - key: app.ini
                path: app.ini
        - name: config-scratchpad
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: gitea
  namespace: gitea
spec:
  ports:
  - name: https
    port: 3001
    protocol: TCP
    targetPort: 3000
  selector:
    app: gitea
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: gitea-ssh
  namespace: gitea
spec:
  ports:
  - name: ssh
    port: 2222
    protocol: TCP
    targetPort: 22
  selector:
    app: gitea
  sessionAffinity: None
  type: ClusterIP
---
