# ksops-secrets-generator.yaml
---
apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: gitea-admin-user
  annotations:
    config.kubernetes.io/function: |
        exec:
          path: ksops
files:
  - gitea-admin-user.encrypted.yaml
---
apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: gitea-internal-token
  labels:
    app: foo
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: ksops
    kustomize.config.k8s.io/needs-hash: "false"
  type: Opaque
files:
- gitea-internal-token.encrypted.yaml
---
apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: gitea-lfs-secret
  labels:
    app: foo
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: ksops
    kustomize.config.k8s.io/needs-hash: "false"
  type: Opaque
files:
- gitea-lfs-secret.encrypted.yaml
---
apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: gitea-secret-key
  labels:
    app: foo
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: ksops
    kustomize.config.k8s.io/needs-hash: "false"
  type: Opaque
files:
- gitea-secret-key.encrypted.yaml
---
