apiVersion: v1
data:
  oidc.config: |
    name: Keycloak
    issuer: https://keycloak.mksybr.com/realms/dev
    clientID: argocd
    clientSecret: $oidc.keycloak.clientSecret
    requestedScopes: ["openid", "profile", "email", "groups"]
  url: https://argocd.mksybr.com
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
data:
  kustomize.buildOptions: "--enable-alpha-plugins --enable-exec"
