apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd
resources:
  - ./namespace.yaml
  - https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
  - ./ingress.yaml
patches:
  - path: argocd-cm.yaml
    target:
      kind: ConfigMap
      name: argocd-cm
  - path: argocd-repo-server-ksops-patch.yaml
    target:
      kind: Deployment
      name: argocd-repo-server
