
# ksops-secrets-generator.yaml
---
apiVersion: viaduct.ai/v1
kind: ksop
metadata:
  name: statping-config
  labels:
    app: foo
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: ksops
    kustomize.config.k8s.io/needs-hash: "false"
  type: Opaque
files:
- statping-config.encrypted.yaml
