# datasette.yml
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: datasette
spec:
  replicas: 1
  selector:
    matchLabels:
      app: datasette
  template:
    metadata:
      labels:
        app: datasette
    spec:
      containers:
      - name: datasette
        image: datasetteproject/datasette
        command:
        - sh
        - -c
        args:
        - |-
          # Install some plugins
          pip install \
            datasette-debug-asgi \
            datasette-cluster-map \
            datasette-psutil
          # Download a DB (using Python because curl/wget are not available)
          python -c 'import urllib.request; urllib.request.urlretrieve("https://global-power-plants.datasettes.com/global-power-plants.db", "/home/global-power-plants.db")'
          # Start Datasette, on 0.0.0.0 to allow external traffic
          datasette -h 0.0.0.0 /home/global-power-plants.db
        ports:
        - containerPort: 8001
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: datasette
  namespace: default
spec:
  ports:
  - name: https
    port: 8001
    protocol: TCP
    targetPort: 8001
  selector:
    app: datasette
  sessionAffinity: None
  type: NodePort
---