# keycloak-config.yaml
apiVersion: v1
data:
    keycloak.conf: |
        # Database
        db=postgres
        # TODO fix permission to run as keycloak
        db-username=postgres
        # TODO fix permission to run as keycloak
        db-password=$POSTGRES_PASSWORD
        db-url-host=postgres-cluster.default.svc.cluster.local
        # Cached prepared statements causes issue on database initialization
        db-url-properties=?preparedStatementCacheQueries=0

        # Load shedding
        http-max-queued-requests=10

        # Observability
        health-enabled=true
        metrics-enabled=true

        # Do not attach route to cookies and rely on the session affinity capabilities from reverse proxy
        #spi-sticky-session-encoder-infinispan-should-attach-route=false

        hostname-url=https://keycloak.mksybr.com/
        hostname-admin-url=https://keycloak.mksybr.com/
        proxy=edge
        quarkus.transaction-manager.enable-recovery=true
kind: ConfigMap
metadata:
    name: keycloak-config
    namespace: keycloak
