kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "3"
  labels:
    app: keycloak
  name: keycloak
  namespace: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: keycloak
    spec:
      containers:
      - args:
        - --verbose
        - start
        env:
        - name: KEYCLOAK_ADMIN
          value: admin
        - name: KEYCLOAK_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: keycloak-admin-user
        - name: KC_PROXY
          value: edge
        image: quay.io/keycloak/keycloak:23.0.4
        name: keycloak
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /realms/master
            port: 8080
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /opt/keycloak/conf/keycloak.conf
          name: config-scratchpad
          readOnly: true
          subPath: keycloak.conf
      initContainers:
      - name: inject-postgres-secret
        image: busybox:1.28
        command: ["sed", "s/${POSTGRES_SUPERUSER_PASSWORD}/$(POSTGRES_SUPERUSER_PASSWORD)/g", "/tmp/keycloak.conf", ">", "/opt/keycloak/conf/keycloak.conf"]
        env:
        - name: POSTGRES_SUPERUSER_PASSWORD
          valueFrom:
            secretKeyRef:
              key: superuser-password
              name: postgres-cluster
        - name: POSTGRES_KEYCLOAK_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: postgres-keycloak-user
        volumeMounts:
        - mountPath:  /opt/keycloak/conf/keycloak.conf
          subPath: keycloak.conf
          readOnly: false
          name: config-scratchpad
        - mountPath: /tmp/keycloak.conf
          name: keycloak-config-file
          readOnly: false
          subPath: keycloak.conf
      - args:
        - psql
        - postgres://postgres:$(POSTGRES_SUPERUSER_PASSWORD)@postgres-cluster.default.svc.cluster.local
        - -c
        - |-
          BEGIN;
            SELECT 'CREATE DATABASE keycloak'
            WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = 'keycloak');
          COMMIT;
          BEGIN;
            SELECT 'CREATE USER keycloak WITH ENCRYPTED PASSWORD "$(POSTGRES_KEYCLOAK_PASSWORD)" CREATEDB'
            WHERE NOT EXISTS (SELECT FROM pg_user WHERE usename = 'keycloak');
            GRANT ALL PRIVILEGES ON DATABASE keycloak TO keycloak;
            GRANT ALL on schema public TO keycloak;
          COMMIT;
        env:
        - name: POSTGRES_SUPERUSER_PASSWORD
          valueFrom:
            secretKeyRef:
              key: superuser-password
              name: postgres-cluster
        - name: POSTGRES_KEYCLOAK_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: postgres-keycloak-user
        image: ongres/postgres-util
        name: setup-keycloak-database-0
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
      volumes:
      - name: config-scratchpad
        emptyDir: {}
      - configMap:
          defaultMode: 420
          name: keycloak-config
        name: keycloak-config-file
      - name: keycloak-realm-file
        secret:
          defaultMode: 420
          secretName: keycloak-realm
