# keycloak.yml
---
apiVersion: v1
kind: Service
metadata:
  name: keycloak
  labels:
    app: keycloak
spec:
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  selector:
    app: keycloak
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: keycloak
  name: keycloak
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: keycloak
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      initContainers:
        - name: setup-keycloak-database
          args:
          - psql
          - postgres://postgres:$(POSTGRES_SUPERUSER_PASSWORD)@postgres-cluster
          - -c
          - |-
            CREATE DATABASE keycloak;
            CREATE USER keycloak WITH PASSWORD '$(POSTGRES_KEYCLOAK_PASSWORD)' CREATEDB;
            GRANT ALL on schema public TO keycloak;
          image: ongres/postgres-util
          resources: {}
          env:
            - name: POSTGRES_SUPERUSER_PASSWORD
              valueFrom: 
                secretKeyRef:
                  name: postgres-cluster 
                  key: superuser-password
            - name: POSTGRES_KEYCLOAK_PASSWORD
              valueFrom: 
                secretKeyRef:
                  name:  postgres-keycloak-user
                  key: password
      containers:
      - args:
        - --verbose
        - start
        env:
        - name: KEYCLOAK_ADMIN
          value: admin
        - name: KEYCLOAK_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: keycloak-admin-user
              key: password
        - name: KC_PROXY
          value: edge
        image: quay.io/keycloak/keycloak:23.0.4
        imagePullPolicy: IfNotPresent
        name: keycloak
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /realms/master
            port: 8080
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /opt/keycloak/conf/keycloak.conf
          name: keycloak-config
          readOnly: true
          subPath: keycloak.conf
        - mountPath: /opt/keycloak/data/import/keycloak-realm
          name: keycloak-realm
          readOnly: true
          subPath: keycloak-realm
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          name: keycloak-config
        name: keycloak-config
      - name: keycloak-realm
        configMap:
          defaultMode: 420
          name: keycloak-realm
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: keycloak
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
    - hosts:
        - keycloak.mksybr.com
    secretName: letsencrypt-prod
  rules:
    - host: keycloak.mksybr.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: keycloak
                port:
                  number: 8080
---