---
apiVersion: viaduct.ai/v1
kind: ksop
metadata:
  name: keycloak-admin-user
  labels:
    app: keycloak
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: ksops
    kustomize.config.k8s.io/needs-hash: "false"
  type: Opaque
files:
  - keycloak/keycloak-admin-user.encrypted.yaml
---
apiVersion: viaduct.ai/v1
kind: ksop
metadata:
  name: postgres-keycloak-user
  labels:
    app: keycloak
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: ksops
    kustomize.config.k8s.io/needs-hash: "false"
  type: Opaque
files:
  - keycloak/postgres-keycloak-user.encrypted.yaml
---
apiVersion: viaduct.ai/v1
kind: ksop
metadata:
  name: keycloak-config
  labels:
    app: keycloak
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: ksops
    kustomize.config.k8s.io/needs-hash: "false"
  type: Opaque
files:
  - keycloak/keycloak-config.encrypted.yaml
# metadata:
    # name: keycloak-realm
    # labels:
      # app: keycloak
    # annotations:
      # kustomize.config.k8s.io/needs-hash: "false"
  # type: Opaque
  # files:
  # - keycloak/keycloak-realm.encrypted.yaml
