---
apiVersion: viaduct.ai/v1
kind: ksop
metadata:
  name: keycloak-admin-user
  labels:
    app: keycloak
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: ksops
    kustomize.config.k8s.io/needs-hash: "false"
  type: Opaque
files:
  - keycloak-admin-user.encrypted.yaml
---
apiVersion: viaduct.ai/v1
kind: ksop
metadata:
  name: postgres-keycloak-user
  labels:
    app: keycloak
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: ksops
    kustomize.config.k8s.io/needs-hash: "false"
  type: Opaque
files:
  - postgres-keycloak-user.encrypted.yaml
