# drone.yml
apiVersion: v1
kind: Service
metadata:
  name: drone
  namespace: drone
spec:
  ports:
  - name: https
    protocol: TCP
    port: 80
    targetPort: 80
  selector:
    app: drone
  sessionAffinity: None
  type: NodePort
