---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: archivebox
spec:
  storageClassName: "local-path"
  volumeName: archivebox
  resources:
    requests:
      storage: 1Gi
  accessModes:
    - ReadWriteMany
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: archivebox
  labels:
    type:
      local
spec:
  local:
    path:
      /data/archivebox
  capacity: 
    storage:
      10Gi
  storageClassName: "local-path"
  accessModes:
    - ReadWriteMany
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - node1
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: archivebox
  name: archivebox
spec:
  selector:
    app: archivebox
  ports:
    - name: http
      port: 8000
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: archivebox
spec:
  selector:
    matchLabels:
      app: archivebox
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: archivebox
    spec:
      initContainers:
        - name: init-archivebox
          image: archivebox/archivebox
          args: ['init']
          volumeMounts:
            - mountPath: /data
              name: archivebox
      containers:
        - name: archivebox
          args: ["server"]
          image: archivebox/archivebox
          ports:
            - containerPort: 8000
              protocol: TCP
              name: http
          resources:
            requests:
              cpu: 50m
              memory: 32Mi
          volumeMounts:
            - mountPath: /data
              name: archivebox
      restartPolicy: Always
      volumes:
        - name: archivebox
          persistentVolumeClaim:
            claimName: archivebox
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: archivebox-letsencrypt-prod
  name: archivebox
  namespace: archivebox
spec:
  ingressClassName: nginx
  rules:
  - host: archivebox.mksybr.com
    http:
      paths:
      - backend:
          service:
            name: archivebox
            port:
              number: 8000
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - archivebox.mksybr.com
    secretName: archivebox-letsencrypt-prod