apiVersion: v1
data:
    password: ENC[AES256_GCM,data:rbYu+TMjUraJXKE+xUR2jPiTm5G47iSK4vTdeG3gpVpkYbJYkeJwq9AfoLONWGqBHODoy8mobx3s73hr,iv:X008+KPjdtFipgJh4LwEhDJtAuaECzaO2jDWlgNlXa8=,tag:XuMmkCcb1i5zTjTzXsdhGw==,type:str]
kind: Secret
metadata:
    name: ENC[AES256_GCM,data:B4C+8uzhade2l4mAAH7wIw==,iv:VJGRTj4pUt9Vly4iwVDrXUF26gfZdy3bZJuP7gR6p20=,tag:9DXmKDEuPTp/rWj9Qwqo0Q==,type:str]
    namespace: ENC[AES256_GCM,data:kQFbDTquiw==,iv:6OQ3cXKyqHHNPSXC4FpnRljib2LAXKjkwCTNhRVgOSo=,tag:yZdwmjTrghUx9P+wLiSRpA==,type:str]
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-01-22T00:33:53Z"
    mac: ENC[AES256_GCM,data:Z6fcssQ9miGTfgLpDWQPfyKkdrCeT1dgnJXtpVcan/8ajohEJmVW/80FbIcowk5Kx3neX0wPLZO5O45mFhn81iFLLko1TdL+bCSNA5XA00a10SBeX02MYoiPiZ/RufkpVAAuwNSXOi+k8LlNumlTSvMepPkQOQ3UvjKnh6HgVHw=,iv:EFvD8IbG31SDl8BniuuiOOWtShO8+QkzIK/c+MVaDYA=,tag:wRCozyU9bvqPc7hNl01zYA==,type:str]
    pgp:
        - created_at: "2024-01-22T00:33:53Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQGMAzipAh8vzmvTAQwArqKOSzbveoOIlMOGfSuR5C+ia2nCDaZPbBOZ4nOmK8r+
            qnVXJ1+stIR/BBDPaSF+fXD4d6otiqK4Eh2n3kTxp9NNq9urc3FuwAlTbWzy+X7s
            4P1H/lChWvNcwCqq2vhBXycH/ov687t2dnALP/8AJ9lAAQCFv7lZ4Y1B243W8CBi
            Z9uXIJK6vvRXEwNt4dT9hmhr+HnBdYmBPgLM+ThWSrPi/GIcVxgvQRfb8gP8XmsR
            puKYQnY80ykh0Z258FJDIcJtCATO60hjO+++1cJw3YB9b6EwhkowUZsFVtk+2Br9
            2jXrQDKc3+zQvnByXcQRiyAbtBsw1BMoDFR0ah1CR+VQC7q4FWxRy8BLAFG0IE1T
            3yZFCEXa7Pb3ISgpjyPH6SWNuX+yHIj5xP0iSeZ55gBvxPZIT1GjiFkqMuA/QqdY
            Gphl/pXoBWxsJOtN+06BOgd1XQZZ9Unoy3M9D/lLYikCIy3NTal1R3oKiTWHka1K
            JHojtPn0+8U3RYZcL6nv0l4BVRbOUlwJjgPcHPKl2n3iszfpPykULW7w+XT9x/b0
            AJomqDf/YvhnIvfRRgcVAOakZHkYuUwMuD/xgQfR9S8c8CFZUd7iqGalr+22yGOo
            BfyleheCb0nGLYZhhGoL
            =9rYr
            -----END PGP MESSAGE-----
          fp: A8F32284234A54A9CD742F91B1AB195143457ABA
    encrypted_regex: data
    version: 3.8.1
