# ksops-secrets-generator.yaml
apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: ksops-secrets-generator
  annotations:
    config.kubernetes.io/function: |
        exec:
          path: ksops
files:
  - gitea/gitea-admin-user.encrypted.yaml
secretFrom:
- metadata:
    name: gitea-internal-token
    labels:
      app: foo
    annotations:
      kustomize.config.k8s.io/needs-hash: "false"
  type: Opaque
  files:
  - gitea/gitea-internal-token.encrypted.yaml
secretFrom:
- metadata:
    name: gitea-lfs-secret
    labels:
      app: foo
    annotations:
      kustomize.config.k8s.io/needs-hash: "false"
  type: Opaque
  files:
  - gitea/gitea-lfs-secret.encrypted.yaml
secretFrom:
- metadata:
    name: gitea-secret-key
    labels:
      app: foo
    annotations:
      kustomize.config.k8s.io/needs-hash: "false"
  type: Opaque
  files:
  - gitea/gitea-secret-key.encrypted.yaml
secretFrom:
- metadata:
    name: keycloak-config
    labels:
      app: foo
    annotations:
      kustomize.config.k8s.io/needs-hash: "false"
  type: Opaque
  files:
  - keycloak/keycloak-config.encrypted.yaml
secretFrom:
- metadata:
    name: keycloak-realm
    labels:
      app: foo
    annotations:
      kustomize.config.k8s.io/needs-hash: "false"
  type: Opaque
  files:
  - keycloak/keycloak-realm.encrypted.yaml
secretFrom:
- metadata:
    name: statping-config
    labels:
      app: foo
    annotations:
      kustomize.config.k8s.io/needs-hash: "false"
  type: Opaque
  files:
  - statping/statping-config.encrypted.yaml