# ksops-secrets-generator.yaml
apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: gitea-admin-user
  annotations:
    config.kubernetes.io/function: |
        exec:
          path: ksops
files:
  - gitea/gitea-admin-user.encrypted.yaml
secretFrom:
- metadata:
    name: gitea-internal-token
    labels:
      app: foo
    annotations:
      config.kubernetes.io/function: |
        exec:
          path: ksops
      kustomize.config.k8s.io/needs-hash: "false"
  type: Opaque
  files:
  - gitea/gitea-internal-token.encrypted.yaml
- metadata:
    name: gitea-lfs-secret
    labels:
      app: foo
    annotations:
      config.kubernetes.io/function: |
        exec:
          path: ksops
      kustomize.config.k8s.io/needs-hash: "false"
  type: Opaque
  files:
  - gitea/gitea-lfs-secret.encrypted.yaml
- metadata:
    name: gitea-secret-key
    labels:
      app: foo
    annotations:
      config.kubernetes.io/function: |
        exec:
          path: ksops
      kustomize.config.k8s.io/needs-hash: "false"
  type: Opaque
  files:
  - gitea/gitea-secret-key.encrypted.yaml
- metadata:
    name: keycloak-admin-user
    labels:
      app: foo
    annotations:
      config.kubernetes.io/function: |
        exec:
          path: ksops
      kustomize.config.k8s.io/needs-hash: "false"
  type: Opaque
  files:
  - keycloak/keycloak-admin-user.encrypted.yaml
- metadata:
    name: postgres-keycloak-user
    labels:
      app: foo
    annotations:
      config.kubernetes.io/function: |
        exec:
          path: ksops
      kustomize.config.k8s.io/needs-hash: "false"
  type: Opaque
  files:
  - keycloak/postgres-keycloak-user.encrypted.yaml
- metadata:
    name: keycloak-config
    labels:
      app: foo
    annotations:
      config.kubernetes.io/function: |
        exec:
          path: ksops
      kustomize.config.k8s.io/needs-hash: "false"
  type: Opaque
  files:
  - keycloak/keycloak-config.encrypted.yaml
# - metadata:
    # name: keycloak-realm
    # labels:
      # app: foo
    # annotations:
      # kustomize.config.k8s.io/needs-hash: "false"
  # type: Opaque
  # files:
  # - keycloak/keycloak-realm.encrypted.yaml
- metadata:
    name: statping-config
    labels:
      app: foo
    annotations:
      config.kubernetes.io/function: |
        exec:
          path: ksops
      kustomize.config.k8s.io/needs-hash: "false"
  type: Opaque
  files:
  - statping/statping-config.encrypted.yaml
