apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
generators:
  - ./ksops-secrets-generator.yaml
resources:
  - https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v1.8.2/deploy/static/provider/cloud/deploy.yaml
  - https://github.com/cert-manager/cert-manager/releases/download/v1.14.1/cert-manager.yaml
  - ./metallb
  - ./clusterissuer.yaml
  - ./archivebox
  - ./datasette
  - ./statping
  - ./stackgres
  - ./postgres
  - ./keycloak
  - ./paperless
  - ./drone
  - ./argocd
  - ./gitea
patches:
  - patch: |-
      - op: replace
        path: /imagePullSecrets/name
        value: docker-registry
    target:
      kind: ServiceAccount
      name: default
  - patch: |-
      - op: add
        path: /metadata/annotations/oci.oraclecloud.com~1load-balancer-type
        value: "nlb"
    target:
      kind: Service
      
      
