---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: vault
spec:
  provider: vault
  parameters:
    roleName: "csi"
---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: vault-database
spec:
  provider: vault
  secretObjects:
  - data:
    - key: keycloak-admin-user
      objectName: secret
    secretName: keycloak-admin-user
    type: Opaque
  parameters:
    vaultAddress: "http://vault.vault:8200"
    roleName: "statping"
    objects: |
      - objectName: "db-password"
        secretPath: "secret/data/db-pass"
        secretKey: "password"