apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: pool
  namespace: metallb-system
spec:
  addresses:
%{ for ip in slice(arm-1vcpu-6gb-us-qas-public_ipv4, 1, 4) ~}
    - ${ip}/32
%{ endfor ~}

