<<<<<<< HEAD
---
- name: Playbook for keycloak Hosts
  hosts: keycloak
  collections:
    - middleware_automation.keycloak
    - middleware_automation.infinispan
    - nginxinc.nginx_config
    - nginxinc.nginx
    - ansible.builtin.package
    - ansible.builtin.file
    - ansible.builtin.include_role
    - ansible.builtin.iptables
  tasks:
    - name: Update Package Cache (apt/Ubuntu)
      tags: always
      become: true
      become_user: root
      apt:
        update_cache: yes
      changed_when: false
      when: ansible_distribution == "Ubuntu"
    - name: Install unzip
      become: true
      become_user: root
      ansible.builtin.package:
        name: unzip
        state: present
    - name: Install java
      become: true
      become_user: root
      ansible.builtin.package:
        name: default-jre
        state: present
    - name: set JAVA (wtf why is this necessary)
      become: true
      become_user: root
      ansible.builtin.lineinfile:
        path: /etc/environment
        state: present
        line: JAVA=/usr/bin/java
    - name: create /etc/sysconfig
      become: true
      become_user: root
      ansible.builtin.file:
        path: /etc/sysconfig
        state: directory
    - name: open http, https, infinispan ports
      become: true
      become_user: root
      ansible.builtin.iptables:
        action: insert
        # TODO(Malik): allow 8080 only from localhost, 80 and 443 globally, and 9990 from 4 peer ips
        chain: INPUT
        match: ["state"]
        ctstate: NEW
        protocol: tcp
        destination_ports:
          - "80"
          - "443"
          - "8080"
          - "8443"
          - "9990"
        jump: ACCEPT
    - set_fact:
        _keycloak_backend: "{{ ansible_play_hosts | map('extract', hostvars, 'inventory_hostname_short') }}"
    - set_fact:
        keycloak_backend: "{{ keycloak_backend|default([]) + [{'address': item + ':8080' }] }}"
      with_items:
        - "{{ _keycloak_backend }}"
    - set_fact:
        keycloak_health: "{{ keycloak_health|default([]) + [{'address': item + ':9990' }] }}"
      with_items:
        - "{{ _keycloak_backend }}"
    - name: Print keycloak_backend
      debug: 
        msg: keycloak_backend={{keycloak_backend}}
    - name: Print keycloak_health
      debug: 
        msg: keycloak_health={{keycloak_health}}
    - name: Configure NGINX
      ansible.builtin.include_role:
        name: nginxinc.nginx_config
        apply:
          become: true
          become_user: root
      vars:
        nginx_config_debug_output: true
        nginx_config_http_template_enable: true
        nginx_config_http_template:
        - template_file: template/nginx/http/default.conf.j2
          deployment_location: /etc/nginx/conf.d/default.conf
          config:
            upstreams:
              - name: keycloak-backend
                servers: "{{ keycloak_backend }}"
                ipv6: false
              - name: keycloak-health
                servers: "{{ keycloak_health }}"
                ipv6: false
            servers:
              - core:
                  listen: 
                    - address: 0.0.0.0
                      port: 80
                      default_server: true
                      server_name: keycloak.mksybr.com
                    # - address: 0.0.0.0
                    #   port: 443
                    #   ssl: false
                    #   default_server: true
                    #   server_name: keycloak.mksybr.com
                locations:
                  # - location: /js/
                  #   proxy:
                  #     pass: http://keycloak-backend/js
                  #     set_header:
                  #       - field: Host
                  #         value: $host
                  #       - field: X-Real-IP
                  #         value: $remote_addr
                  #       - field: X-Forwarded-For
                  #         value: $proxy_add_x_forwarded_for
                  #       - field: X-Forwarded-Proto
                  #         value: $scheme
                  # - location: /realms/
                  #   proxy:
                  #     pass: http://keycloak-backend/realms
                  #     set_header:
                  #       - field: Host
                  #         value: $host
                  #       - field: X-Real-IP
                  #         value: $remote_addr
                  #       - field: X-Forwarded-For
                  #         value: $proxy_add_x_forwarded_for
                  #       - field: X-Forwarded-Proto
                  #         value: $scheme
                  # - location: /resources/
                  #   proxy:
                  #     pass: http://keycloak-backend/resources
                  #     set_header:
                  #       - field: Host
                  #         value: $host
                  #       - field: X-Real-IP
                  #         value: $remote_addr
                  #       - field: X-Forwarded-For
                  #         value: $proxy_add_x_forwarded_for
                  #       - field: X-Forwarded-Proto
                  #         value: $scheme
                  # - location: /robots.txt
                  #   proxy:
                  #     pass: http://keycloak-backend/robots.txt
                  #     set_header:
                  #       - field: Host
                  #         value: $host
                  #       - field: X-Real-IP
                  #         value: $remote_addr
                  #       - field: X-Forwarded-For
                  #         value: $proxy_add_x_forwarded_for
                  #       - field: X-Forwarded-Proto
                  #         value: $scheme
                  - location: / # TODO remove
                    proxy:
                      pass: http://keycloak-backend/
                      set_header:
                        - field: Host
                          value: $host
                        - field: X-Forwarded-Host
                          value: $host
                        - field: X-Forwarded-Server
                          value: $host
                        # - field: X-Forwarded-Port
                        #   value: $mapped_server_port
                        - field: X-Real-IP
                          value: $remote_addr
                        - field: X-Forwarded-For
                          value: $proxy_add_x_forwarded_for
                        - field: X-Forwarded-Proto
                          value: $scheme
                        - field: Accept-Encoding
                          value: "*"
    - name: Include nginx role
      ansible.builtin.include_role:
        name: nginxinc.nginx
        apply:
          become: true
          become_user: root
      vars:
        nginx_debug_output: true
    - name: Include keycloak role
      ansible.builtin.include_role:
        name: keycloak
      vars:
        keycloak_java_home: "/usr/lib/jvm/default-java"
        # keycloak_host: keycloak.mksybr.com
        keycloak_service_restart_on_failure: true
        # keycloak_db_enabled: true
        keycloak_frontend_url: http://keycloak.mksybr.com
        keycloak_admin_password: "MdEh5CSlSPuQWZYEKIR0c0uZ97r14hZUT+lsFTlQd4MdxsoqkgbVMMqLxDoGDQwoOt+nT7pr0Gnl"
      args:
        apply:
          environment:
            PROXY_ADDRESS_FORWARDING: true
            KC_HTTP_RELATIVE_PATH: /
            KC_PROXY: edge
            KC_HOSTNAME_URL: http://keycloak.mksybr.com:80/

||||||| fd9f660
=======
---
- name: Playbook for keycloak Hosts
  hosts: keycloak
  collections:
    - middleware_automation.keycloak
    - middleware_automation.infinispan
    - nginxinc.nginx_config
    - nginxinc.nginx
    - ansible.builtin.package
    - ansible.builtin.file
    - ansible.builtin.include_role
    - ansible.builtin.iptables
  tasks:
    - name: Update Package Cache (apt/Ubuntu)
      tags: always
      become: true
      become_user: root
      apt:
        update_cache: yes
      changed_when: false
      when: ansible_distribution == "Ubuntu"
    - name: Install unzip
      become: true
      become_user: root
      ansible.builtin.package:
        name: unzip
        state: present
    - name: Install java
      become: true
      become_user: root
      ansible.builtin.package:
        name: default-jre
        state: present
    - name: set JAVA (wtf why is this necessary)
      become: true
      become_user: root
      ansible.builtin.lineinfile:
        path: /etc/environment
        state: present
        line: JAVA=/usr/bin/java
    - name: create /etc/sysconfig
      become: true
      become_user: root
      ansible.builtin.file:
        path: /etc/sysconfig
        state: directory
    - name: open http, https, infinispan ports
      become: true
      become_user: root
      ansible.builtin.iptables:
        action: insert
        # TODO(Malik): allow 8080 only from localhost, 80 and 443 globally, and 9990 from 4 peer ips
        chain: INPUT
        match: ["state"]
        ctstate: NEW
        protocol: tcp
        destination_ports:
          - "80"
          - "443"
          - "8080"
          - "8443"
          - "9990"
        jump: ACCEPT
    - set_fact:
        _keycloak_backend: "{{ ansible_play_hosts | map('extract', hostvars, 'inventory_hostname_short') }}"
    - set_fact:
        keycloak_backend: "{{ keycloak_backend|default([]) + [{'address': item + ':8080' }] }}"
      with_items:
        - "{{ _keycloak_backend }}"
    - set_fact:
        keycloak_health: "{{ keycloak_health|default([]) + [{'address': item + ':9990' }] }}"
      with_items:
        - "{{ _keycloak_backend }}"
    - name: Print keycloak_backend
      debug: 
        msg: keycloak_backend={{keycloak_backend}}
    - name: Print keycloak_health
      debug: 
        msg: keycloak_health={{keycloak_health}}
    - name: Configure NGINX
      ansible.builtin.include_role:
        name: nginxinc.nginx_config
        apply:
          become: true
          become_user: root
      vars:
        keycloak_java_home: "/usr/lib/jvm/default-java"
        # keycloak_host: keycloak.mksybr.com
        keycloak_service_restart_on_failure: true
        # keycloak_db_enabled: true
        keycloak_admin_password: ""
        nginx_config_debug_output: true
        nginx_config_http_template_enable: true
        nginx_config_http_template:
        - template_file: template/nginx/http/default.conf.j2
          deployment_location: /etc/nginx/conf.d/default.conf
          config:
            upstreams:
              - name: keycloak-backend
                servers: "{{ keycloak_backend }}"
                ipv6: false
              - name: keycloak-health
                servers: "{{ keycloak_health }}"
                ipv6: false
            servers:
              - core:
                  listen: 
                    - address: 0.0.0.0
                      port: 80
                      default_server: true
                      server_name: keycloak.mksybr.com
                    # - address: 0.0.0.0
                    #   port: 443
                    #   ssl: false
                    #   default_server: true
                    #   server_name: keycloak.mksybr.com
                locations:
                  # - location: /js/
                  #   proxy:
                  #     pass: http://keycloak-backend/js
                  #     set_header:
                  #       - field: Host
                  #         value: $host
                  #       - field: X-Real-IP
                  #         value: $remote_addr
                  #       - field: X-Forwarded-For
                  #         value: $proxy_add_x_forwarded_for
                  #       - field: X-Forwarded-Proto
                  #         value: $scheme
                  # - location: /realms/
                  #   proxy:
                  #     pass: http://keycloak-backend/realms
                  #     set_header:
                  #       - field: Host
                  #         value: $host
                  #       - field: X-Real-IP
                  #         value: $remote_addr
                  #       - field: X-Forwarded-For
                  #         value: $proxy_add_x_forwarded_for
                  #       - field: X-Forwarded-Proto
                  #         value: $scheme
                  # - location: /resources/
                  #   proxy:
                  #     pass: http://keycloak-backend/resources
                  #     set_header:
                  #       - field: Host
                  #         value: $host
                  #       - field: X-Real-IP
                  #         value: $remote_addr
                  #       - field: X-Forwarded-For
                  #         value: $proxy_add_x_forwarded_for
                  #       - field: X-Forwarded-Proto
                  #         value: $scheme
                  # - location: /robots.txt
                  #   proxy:
                  #     pass: http://keycloak-backend/robots.txt
                  #     set_header:
                  #       - field: Host
                  #         value: $host
                  #       - field: X-Real-IP
                  #         value: $remote_addr
                  #       - field: X-Forwarded-For
                  #         value: $proxy_add_x_forwarded_for
                  #       - field: X-Forwarded-Proto
                  #         value: $scheme
                  - location: / # TODO remove
                    proxy:
                      pass: http://keycloak-backend/
                      set_header:
                        - field: Host
                          value: $host
                        - field: X-Forwarded-Host
                          value: $host
                        - field: X-Forwarded-Server
                          value: $host
                        # - field: X-Forwarded-Port
                        #   value: $mapped_server_port
                        - field: X-Real-IP
                          value: $remote_addr
                        - field: X-Forwarded-For
                          value: $proxy_add_x_forwarded_for
                        - field: X-Forwarded-Proto
                          value: $scheme
                        - field: Accept-Encoding
                          value: "*"
    - name: Include nginx role
      ansible.builtin.include_role:
        name: nginxinc.nginx
        apply:
          become: true
          become_user: root
      vars:
        nginx_debug_output: true
    - name: Include keycloak role
      ansible.builtin.include_role:
        name: keycloak
      vars:
        keycloak_java_home: "/usr/lib/jvm/default-java"
        # keycloak_host: keycloak.mksybr.com
        keycloak_service_restart_on_failure: true
        # keycloak_db_enabled: true
        keycloak_frontend_url: http://keycloak.mksybr.com
        keycloak_admin_password: ""
      args:
        apply:
          environment:
            PROXY_ADDRESS_FORWARDING: true
            KC_HTTP_RELATIVE_PATH: /
            KC_PROXY: edge
            KC_HOSTNAME_URL: http://keycloak.mksybr.com:80/

>>>>>>> master
