---
- name: Playbook for keycloak Hosts
  hosts: oracle_arm
  collections:
    - middleware_automation.keycloak
    - middleware_automation.infinispan
    - nginxinc.nginx
    - ansible.builtin.package
    - ansible.builtin.file
    - ansible.builtin.include_role
    - ansible.builtin.iptables
  tasks:
    - name: Update Package Cache (apt/Ubuntu)
      tags: always
      become: true
      become_user: root
      apt:
        update_cache: yes
      changed_when: false
      when: ansible_distribution == "Ubuntu"
    - name: Install unzip
      become: true
      become_user: root
      ansible.builtin.package:
        name: unzip
        state: present
    - name: Install java
      become: true
      become_user: root
      ansible.builtin.package:
        name: default-jre
        state: present
    - name: set JAVA (wtf why is this necessary)
      become: true
      become_user: root
      ansible.builtin.lineinfile:
        path: /etc/environment
        state: present
        line: JAVA=/usr/bin/java
    - name: create /etc/sysconfig
      become: true
      become_user: root
      ansible.builtin.file:
        path: /etc/sysconfig
        state: directory
    - name: open http, https, infinispan ports
      become: true
      become_user: root
      ansible.builtin.iptables:
        action: insert
        chain: INPUT
        match: ["state"]
        ctstate: NEW
        protocol: tcp
        destination_ports:
          - "80"
          - "443"
          - "8080"
          - "8443"
          - "9990"
          - "11222"
        jump: ACCEPT
    - name: Include infinispan role
      ansible.builtin.include_role:
        name: infinispan
      vars:
        infinispan_java_home: "/usr/lib/jvm/default-java"
        infinispan_supervisor_password: "jChhT4AUnUZ+S3iTHwGKhvQmbp4GONn3jD1ch4Di0u0"
        infinispan_users: []
    - name: Include keycloak role
      ansible.builtin.include_role:
        name: keycloak
      vars:
        keycloak_ha_enabled: True
        keycloak_java_home: "/usr/lib/jvm/default-java"
        # keycloak_host: keycloak.mksybr.com
        keycloak_service_restart_on_failure: true
        keycloak_admin_password: "MdEh5CSlSPuQWZYEKIR0c0uZ97r14hZUT+lsFTlQd4MdxsoqkgbVMMqLxDoGDQwoOt+nT7pr0Gnl" 
        keycloak_infinispan_trust_store_password: "jChhT4AUnUZ+S3iTHwGKhvQmbp4GONn3jD1ch4Di0u0"
        # TODO replace with var
    - name: Include nginx role
      ansible.builtin.include_role:
        name: ansible-role-nginx
      vars:
        nginx_debug_output: true
