- name: keycloak
  hosts: keycloak
  vars:
    keycloak_quarkus_admin_pass: "remembertochangeme"
    keycloak_quarkus_host: localhost
    keycloak_quarkus_port: 8443
    keycloak_quarkus_log: file
    keycloak_quarkus_proxy_mode: none
  roles:
    -  { role: middleware_automation.keycloak.keycloak_quarkus, tags: [ 'keycloak' ], when: "keycloak is defined" }

- hosts: syncthing
  vars:
    user: syncthing
    group: syncthing
    config_directory: /home/{{ user }}/.config/syncthing
    data_directory: /home/{{ user }}/.local/share/syncthing
    packages:
      syncthing
  tasks:
    - name: open firewall
      become: true
      become_user: root
      block:
        - ansible.builtin.iptables:
            chain: INPUT
            src_range: 100.64.0.0-100.127.255.255
            protocol: tcp
            destination_ports:
              - 22000
        - ansible.builtin.iptables:
            chain: INPUT
            src_range: 100.64.0.0-100.127.255.255
            protocol: udp
            destination_ports:
              - 21027
    - name: create service account
      become: true
      become_user: root
      ansible.builtin.user:
        name: "{{ user }}"
    - name: enforces service directories
      become: true
      become_user: root
      ansible.builtin.file:
        state: directory
        path: "{{ item }}"
        owner: "{{ user }}"
        mode: 0750
      loop:
        - "{{ config_directory }}"
        - "{{ data_directory }}"
    - name: Install syncthing
      ansible.builtin.package:
        name: "{{ packages }}"
    - name: Configure syncthing
      ansible.builtin.copy:
        content: "{{ lookup('community.sops.sops', './syncthing/config.xml.enc', rstrip=false) }}"
        dest: /home/{{ user }}/.config/syncthing/config.xml
        owner: "{{ user }}"
        group: "{{ user }}"
        mode: 0600
      args:
        creates: /home/{{ user }}/.config/syncthing/config.xml
      no_log: true
    - name: Start and enable services
      ansible.builtin.service:
        name: "syncthing@{{ user }}"
        state: started
    
- name: nginx
  hosts: 
    - syncthing
    - keycloak
  tasks:
    - name: Install NGINX
      ansible.builtin.include_role:
        name: nginxinc.nginx
        apply:
          become: yes
          become_user: root
      vars:
        nginx_install_from: "os_repository"
        nginx_logrotate_conf:
          paths: /var/log/nginx/*.log
          options:
            - daily
            - missingok
            - rotate 14
            - compress
            - delaycompress
            - notifempty
            - sharedscripts
    - name: Configure NGINX
      become: true
      become_user: root
      ansible.builtin.copy:
        src: ./nginx
        dest: /etc/
        owner: root
        group: root
    - name: Install certbot
      become: true
      become_user: root
      ansible.builtin.package:
        name:
        - certbot
        - letsencrypt
        - python3-certbot-nginx
        - python3-certbot-dns-digitalocean
        state: present
    - name: Add DigitalOcean credential
      ansible.builtin.copy:
        content: "{{ lookup('community.sops.sops', './certbot/digitalocean.ini.enc', rstrip=false) }}"
        dest: /tmp/digitalocean.ini
        owner: "{{ user }}"
        group: "{{ user }}"
        mode: 0600
      args:
        creates: /tmp/digitalocean.ini
      no_log: true
      when:
        - false
    - name: ACME certificate
      become: true
      become_user: root
      ansible.builtin.command: sudo certbot certonly --dns-digitalocean --dns-digitalocean-credentials /tmp/digitalocean.ini -d *.mksybr.com -m mksybr@gmail.com --agree-tos --no-eff-email --preferred-challenges dns
      args: 
        creates: /etc/letsencrypt/live/mksybr.com/
    - name: Enable NGINX sites
      become: true
      become_user: root
      ansible.builtin.file:
        src: "/etc/nginx/sites-available/{{ item }}.conf"
        dest: "/etc/nginx/sites-enabled/{{ item }}.conf"
        force: yes
        owner: root
        group: root
        state: link
      loop: [ keycloak, syncthing ]
    # - name: Restart NGINX service
    #   ansible.builtin.systemd_service:
    #     name: nginx
    #     state: restarted
