- src: https://github.com/Aeyk/syncthing-ansible-role.git
  version: master
  name: syncthing

- src: https://github.com/Aeyk/keycloak-ansible-role.git
  version: main
  name: middleware_automation.keycloak

- src: nginxinc.nginx_config
  name: nginxinc.nginx_config

- src: nginxinc.nginx
  name: nginxinc.nginx

- src: community.sops
  name: community.sops
