# postgres-cluster.yml
---
apiVersion: stackgres.io/v1
kind: SGInstanceProfile
metadata:
  namespace: default
  name: size-small
spec:
  cpu: "500m"
  memory: "1Gi"
---
apiVersion: stackgres.io/v1
kind: SGPostgresConfig
metadata:
  namespace: default
  name: pgconfig1
spec:
  postgresVersion: "16"
  postgresql.conf:
    shared_buffers: '512MB'
    random_page_cost: '1.5' 
    password_encryption: 'scram-sha-256'
    log_checkpoints: 'on'
---
apiVersion: stackgres.io/v1
kind: SGPoolingConfig
metadata:
  namespace: default
  name: poolconfig1
spec:
  pgBouncer:
    pgbouncer.ini:
      pgbouncer:
        pool_mode: transaction
        max_client_conn: '1000'
        default_pool_size: '80'
---
apiVersion: stackgres.io/v1
kind: SGCluster
metadata:
  namespace: default
  name: postgres-cluster
spec:
  postgres:
    version: '16.1'
  instances: 1 
  sgInstanceProfile: 'size-small'
  pods:
    persistentVolume:
      size: '10Gi'
  configurations:
    sgPostgresConfig: 'pgconfig1'
    sgPoolingConfig: 'poolconfig1'
    # backups:
    # - sgObjectStorage: 'backupconfig1'
    #   cronSchedule: '*/5 * * * *'
    #   retention: 6
  managedSql:
    scripts:
    - sgScript: cluster-scripts
---
